### ISSUE TITLE
Feature Request: block lists?

### ISSUE THREAD

**Issue by rtxanson** [kawamataryo/sky-follower-bridge#46]
Feels like it wouldn't be too hard to get Sky Follower Bridge to work on the blocks page on twitter, then let people block on Bluesky instead of follow. I don't know the codebase, is this reasonably achievable?

**Comment by kawamataryo** [comment]
@rtxanson 

Thank you for raising this issue. That feature is already available! By enabling the Sky Follower Bridge at `https://x.com/settings/blocked/all` , you can block users instead of following them.

<img width="831" alt="image" src="https://github.com/user-attachments/assets/53ee0197-19c8-42f0-a6d6-c7ed2ca5564b">
